site_name: Zillona Org
nav:
  - Container Orchestration: orchestration.md
  - TableTech: tabletech.md
  - Dojo: dojo.md
  - Skill Tree: skill_tree.md
theme:
  name: mkdocs
  locale: en
  color_mode: auto
  nav_style: dark
